1).How to Creating a 3x3 Identity Matrix with Float Data Type?

Ans:-To create a 3x3 identity matrix with float data type in Python, use the numpy library.

code:

import numpy as np

identity_matrix = np.identity(3, dtype=float)

print(identity_matrix)

In [2]:
#2). Create a 1D Array with Random Values between 0 and 1.

import numpy as np
a = np.random.rand(10)
print(a)

[0.36164155 0.8249644  0.17889556 0.72717841 0.95484195 0.74111773
 0.65409915 0.32564741 0.48105495 0.91998357]


In [6]:
#3). Create a 2D Array with Random Integer Values.

import numpy as np
a = np.array([[0.255,0.052],[0.999,0.0662]])
print(a)

[[0.255  0.052 ]
 [0.999  0.0662]]


In [24]:
#4).Creating an Array Using a Custom Function.

import numpy as np

def create_custom_array(size, value):
    return np.full(size, value)

array = create_custom_array((3, 3), [[25,100,1125],[215,410,801],[321,2152,225]])
print(array)

[[  25  100 1125]
 [ 215  410  801]
 [ 321 2152  225]]


In [25]:
#5).Reshaping a 1D Array into a 2D Array

import numpy as np

one_d_array = np.array([1, 2, 3, 4, 5, 6])

two_d_array = one_d_array.reshape((2, 3))

print(two_d_array)


[[1 2 3]
 [4 5 6]]


In [32]:
#6).How to Creating a 3x3 Array of Ones?

import numpy as np

ones_array = np.ones([3, 3])

print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
#7).How to get the common items between two pythons NumPy?

a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [34]:
#8). From array a remove all items present in array b

a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


In [35]:
#9).Limit the number of items printed in python NumPy array a to a maximum of 6 elements.

a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


In [37]:
#10).Drop all nan values from a 1D NumPy array.

#input : np.array([1,2,3,np.nan,5,6,7,np.nan])
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a[~np.isnan(a)])

[1. 2. 3. 5. 6. 7.]


In [38]:
#11).Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

a = np.arange(20)
b = np.arange(1,21).reshape(4,5)
print(a)
print(b)

[ 0  1  2 ... 17 18 19]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [52]:
#12).Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. Change its data type to float64 and verify the change.

import numpy as np

# Create a 3D NumPy array of shape (2, 3, 4)
array_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                     [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

print(array_3d)

print("array shape is ",array_3d.shape)
print("array size is",array_3d.size)
print("array dimension is",array_3d.ndim)
print("data type of array is",array_3d.dtype)

array_3d_float64 = array_3d.astype(np.float64)
print("data type of array is",array_3d_float64.dtype)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
array shape is  (2, 3, 4)
array size is 24
array dimension is 3
data type of array is int64
data type of array is float64


In [54]:
#13). Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened array matches the original.

import numpy as np

original_array = np.arange(12)

reshaped_array = original_array.reshape((3, 4))

flattened_array = reshaped_array.ravel()

arrays_match = np.array_equal(original_array, flattened_array)

print("Original array:", original_array)
print("Reshaped array:\n", reshaped_array)
print("Flattened array:", flattened_array)
print("Arrays match:", arrays_match)


Original array: [ 0  1  2 ...  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2 ...  9 10 11]
Arrays match: True


In [55]:
#14).Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division. Explain the behavior when dividing by zero.

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [56]:
#15).Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting rules apply in this scenario.

import numpy as np

array_2d = np.array([[1], [2], [3]])

array_1d = np.array([4, 5, 6])

result = array_2d + array_1d

print("2D Array:\n", array_2d)
print("1D Array:", array_1d)
print("Result of Broadcasting:\n", result)


2D Array:
 [[1]
 [2]
 [3]]
1D Array: [4 5 6]
Result of Broadcasting:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [57]:
#16).Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5.

import numpy as np

random_array = np.random.randint(0, 11, size=(3, 4))
print("Original array:\n", random_array)

mask = random_array > 5
print("Boolean mask:\n", mask)

random_array[mask] = 5
print("Modified array:\n", random_array)


Original array:
 [[ 5 10  1  6]
 [ 9  1 10 10]
 [ 1  6  9  9]]
Boolean mask:
 [[False  True False  True]
 [ True False  True  True]
 [False  True  True  True]]
Modified array:
 [[5 5 1 5]
 [5 1 5 5]
 [1 5 5 5]]


In [58]:
#17). Given a 4x4 array of random integers, use indexing and slicing to extract: The entire second row The last column The subarray consisting of the first two rows and first two columns.

import numpy as np

array_4x4 = np.random.randint(0, 11, size=(4, 4))
print("Original array:\n", array_4x4)

second_row = array_4x4[1, :]
print("\nEntire second row:", second_row)

last_column = array_4x4[:, -1]
print("\nLast column:", last_column)

subarray = array_4x4[:2, :2]
print("\nSubarray (first two rows and first two columns):\n", subarray)


Original array:
 [[ 8  5  9 10]
 [ 7  7  0 10]
 [ 5  7  7  9]
 [ 9  3  5  2]]

Entire second row: [ 7  7  0 10]

Last column: [10 10  9  2]

Subarray (first two rows and first two columns):
 [[8 5]
 [7 7]]


18).Describe a practical example where NumPy can be used in EDA,
AI, ML, and DL, and implement a NumPy solution for a simple task in each
area.

Ans:- NumPy can be used in Exploratory Data Analysis (EDA) for calculating statistics, in Artificial Intelligence (AI) for normalizing image pixels, in Machine Learning (ML) for data splitting, and in Deep Learning (DL) for initializing neural network weights. It enhances workflows across these areas with efficient computations.

In [59]:
#19).Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix.

import numpy as np
matrix = np.random.rand(4, 4)
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 1.2993892  -0.67286159 -0.13046633  0.06301719]

Eigenvectors:
[[-0.61950815 -0.64210989 -0.24399193 -0.06714275]
 [-0.26190604 -0.1282388  -0.62196757 -0.69452044]
 [-0.49351514  0.61119211  0.6696992   0.10029317]
 [-0.55141426  0.44462783  0.32423334  0.70927745]]


In [60]:
#20).Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original.

import numpy as np

original_array = np.arange(27)

reshaped_array = original_array.reshape((3, 3, 3))

flattened_array = reshaped_array.ravel()

arrays_match = np.array_equal(original_array, flattened_array)

print("Original array:\n", original_array)
print("\nReshaped array:\n", reshaped_array)
print("\nFlattened array:\n", flattened_array)
print("\nArrays match:", arrays_match)

Original array:
 [ 0  1  2 ... 24 25 26]

Reshaped array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened array:
 [ 0  1  2 ... 24 25 26]

Arrays match: True


In [61]:
#21).Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset.

import numpy as np
import time

A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

start_time = time.time()
result_dot = np.dot(A, B)
time_dot = time.time() - start_time

start_time = time.time()
result_at = A @ B
time_at = time.time() - start_time

results_match = np.array_equal(result_dot, result_at)

print(f"Results match: {results_match}")
print(f"Time taken with np.dot(): {time_dot:.6f} seconds")
print(f"Time taken with @ operator: {time_at:.6f} seconds")


Results match: True
Time taken with np.dot(): 0.066812 seconds
Time taken with @ operator: 0.065318 seconds


In [62]:
#22).Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting.

import numpy as np

# Create a 3D array of shape (2, 1, 4)
array_3d = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])

# Create a 2D array of shape (4, 1)
array_2d = np.array([[1], [2], [3], [4]])

# Perform element-wise addition using broadcasting
result_broadcast = array_3d + array_2d

print("3D Array:\n", array_3d)
print("2D Array:\n", array_2d)
print("Result using broadcasting:\n", result_broadcast)


3D Array:
 [[[1 2 3 4]]

 [[5 6 7 8]]]
2D Array:
 [[1]
 [2]
 [3]
 [4]]
Result using broadcasting:
 [[[ 2  3  4  5]
  [ 3  4  5  6]
  [ 4  5  6  7]
  [ 5  6  7  8]]

 [[ 6  7  8  9]
  [ 7  8  9 10]
  [ 8  9 10 11]
  [ 9 10 11 12]]]


In [65]:
#23).Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged.

import numpy as np

array_2d = np.random.rand(4, 5)  # Example shape (4, 5)
print("Original array:\n", array_2d)

mask = array_2d < 0.5
print("\nBoolean mask:\n", mask)

array_2d[mask] = np.square(array_2d[mask])
print("\nModified array:\n", array_2d)

Original array:
 [[0.37162548 0.4256248  0.16407944 0.61886687 0.54043608]
 [0.05192785 0.89060694 0.07846875 0.59540302 0.98650208]
 [0.81786338 0.50139079 0.11696743 0.30434755 0.85161511]
 [0.2854375  0.38049468 0.43417048 0.76901875 0.87726373]]

Boolean mask:
 [[ True  True  True False False]
 [ True False  True False False]
 [False False  True  True False]
 [ True  True  True False False]]

Modified array:
 [[0.1381055  0.18115647 0.02692206 0.61886687 0.54043608]
 [0.0026965  0.89060694 0.00615734 0.59540302 0.98650208]
 [0.81786338 0.50139079 0.01368138 0.09262743 0.85161511]
 [0.08147457 0.1447762  0.18850401 0.76901875 0.87726373]]


In [67]:
#25).Given a 5x5 array of sequential integers, use slicing to: Extract the diagonal elements Replace the elements of the middle row with zeros Flip the array vertically and horizontally

import numpy as np

array_5x5 = np.arange(1, 26).reshape((5, 5))
print("Original array:\n", array_5x5)

diagonal_elements = np.diag(array_5x5)
print("\nDiagonal elements:", diagonal_elements)

array_5x5[2, :] = 0
print("\nArray with middle row replaced with zeros:\n", array_5x5)

flipped_array = np.flip(array_5x5)
print("\nFlipped array:\n", flipped_array)


Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Diagonal elements: [ 1  7 13 19 25]

Array with middle row replaced with zeros:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Flipped array:
 [[25 24 23 22 21]
 [20 19 18 17 16]
 [ 0  0  0  0  0]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [68]:
#25).Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis.

import numpy as np

array_4d = np.random.randint(0, 11, size=(2, 3, 4, 5))
print("Original 4D array:\n", array_4d)

subarray = array_4d[0, :, :, :]
print("\nExtracted subarray:\n", subarray)

mean_subarray = np.mean(subarray, axis=1)
print("\nMean along the second axis:\n", mean_subarray)

Original 4D array:
 [[[[ 9  7  4  0  9]
   [ 2  6  1  0  1]
   [ 3  2  7  0  2]
   [10  1 10  7  9]]

  [[ 5  8  9  1  8]
   [ 5  3  2  5  9]
   [ 3 10  6 10 10]
   [ 4 10  1  6  0]]

  [[ 0  7  5  8  5]
   [ 8  3  6  2  4]
   [ 1  8  2  2  5]
   [ 7  8  1  6  5]]]


 [[[ 5  4  8  4  7]
   [10  0  6  1  5]
   [ 1  4  4  2 10]
   [ 2  7  8  5  3]]

  [[ 1 10  7  9  5]
   [ 4  7  2 10  5]
   [ 6  7  9  4  6]
   [ 7  4  8  0  4]]

  [[ 8 10 10  8  2]
   [ 0 10  6  3  1]
   [ 6  2  7  8  9]
   [ 3  6  3  3  4]]]]

Extracted subarray:
 [[[ 9  7  4  0  9]
  [ 2  6  1  0  1]
  [ 3  2  7  0  2]
  [10  1 10  7  9]]

 [[ 5  8  9  1  8]
  [ 5  3  2  5  9]
  [ 3 10  6 10 10]
  [ 4 10  1  6  0]]

 [[ 0  7  5  8  5]
  [ 8  3  6  2  4]
  [ 1  8  2  2  5]
  [ 7  8  1  6  5]]]

Mean along the second axis:
 [[6.   4.   5.5  1.75 5.25]
 [4.25 7.75 4.5  5.5  6.75]
 [4.   6.5  3.5  4.5  4.75]]


In [69]:
#26)Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality.

import numpy as np

original_array = np.arange(200).reshape((10, 20))
print("Original array shape:", original_array.shape)

reshaped_20_10 = original_array.reshape((20, 10))
print("Reshaped (20, 10) array shape:", reshaped_20_10.shape)

reshaped_5_40 = original_array.reshape((5, 40))
print("Reshaped (5, 40) array shape:", reshaped_5_40.shape)


Original array shape: (10, 20)
Reshaped (20, 10) array shape: (20, 10)
Reshaped (5, 40) array shape: (5, 40)


In [71]:
#27).Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations.


import numpy as np

# Generate a large 2D array (e.g., 100x100) with random integers between 0 and 10
large_array = np.random.randint(0, 11, size=(100, 100))
print("Original array shape:", large_array.shape)

# Reshape the array to (50, 200)
reshaped_50_200 = large_array.reshape((50, 200))
print("Reshaped (50, 200) array shape:", reshaped_50_200.shape)

# Reshape the array to (10, 1000)
reshaped_10_1000 = large_array.reshape((10, 1000))
print("Reshaped (10, 1000) array shape:", reshaped_10_1000.shape)

# Flatten the array using ravel()
flattened_array = large_array.ravel()
print("Flattened array shape:", flattened_array.shape)

# Perform matrix multiplication (e.g., A * A.T)
result_matrix_multiplication = np.dot(reshaped_50_200, reshaped_50_200.T)
print("Result of matrix multiplication shape:", result_matrix_multiplication.shape)

# Create a square submatrix for inversion (e.g., 10x10 from the original array)
square_submatrix = large_array[:10, :10]
inverse_matrix = np.linalg.inv(square_submatrix)
print("Inverse matrix shape:", inverse_matrix.shape)

Original array shape: (100, 100)
Reshaped (50, 200) array shape: (50, 200)
Reshaped (10, 1000) array shape: (10, 1000)
Flattened array shape: (10000,)
Result of matrix multiplication shape: (50, 50)
Inverse matrix shape: (10, 10)


In [72]:
#28).Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero. Verify the result.

import numpy as np

matrix = np.random.randint(1, 11, size=(6, 6))
print("Original matrix:\n", matrix)

upper_triangular = np.triu(matrix)
print("\nUpper triangular matrix:\n", upper_triangular)

matrix[np.tril_indices(6, -1)] = 0
print("\nMatrix with lower triangular part set to zero:\n", matrix)

assert np.array_equal(matrix, upper_triangular), "The matrices do not match"
print("\nVerification successful: The matrices match.")

Original matrix:
 [[ 1 10  4 10  5  2]
 [ 6  1  4  9  9  9]
 [ 6  3  5  6  3  7]
 [ 4  4 10  3  8  6]
 [ 3  4  7  1  9  5]
 [ 1  2  1  1  9  3]]

Upper triangular matrix:
 [[ 1 10  4 10  5  2]
 [ 0  1  4  9  9  9]
 [ 0  0  5  6  3  7]
 [ 0  0  0  3  8  6]
 [ 0  0  0  0  9  5]
 [ 0  0  0  0  0  3]]

Matrix with lower triangular part set to zero:
 [[ 1 10  4 10  5  2]
 [ 0  1  4  9  9  9]
 [ 0  0  5  6  3  7]
 [ 0  0  0  3  8  6]
 [ 0  0  0  0  9  5]
 [ 0  0  0  0  0  3]]

Verification successful: The matrices match.
